name: Calendar Sync

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  sync-calendars:
    runs-on: ubuntu-latest
    
    steps:
      - name: Call calendar sync endpoint
        run: |
          echo "Calling endpoint..."
          curl -v https://www.partysnap.co.uk/api/calendar/scheduled-sync